In [4]:
import torch

#Scalar : Zero dimension tensor
scalar =torch.tensor(7)
scalar

tensor(7)

In [6]:
#check Scalar dimension
scalar.ndim

0

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [12]:
#A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.ndim
# number of dim counted by [ 

1

In [16]:
#shape
vector.shape
# vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [18]:
#matrix
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
tensor =torch.tensor([[[1, 2, 3], [3, 6, 9],[2, 4, 5]]])
tensor


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [38]:
tensor.ndim


3

In [36]:
tensor.shape
#means there's 1 dimension of 3 by 3.

torch.Size([1, 3, 3])

In [40]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8810, 0.5371, 0.6764, 0.4295],
         [0.3031, 0.2405, 0.7145, 0.4834],
         [0.5310, 0.2044, 0.5873, 0.1162]]),
 torch.float32)

In [42]:
#Range -> (torch.range deprecated 
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#torch.cuda the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA)
#https://pytorch.org/docs/stable/tensors.html#data-types

In [50]:
#create a tensor with dtype=torch.float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [52]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2094, 0.5545, 0.4530, 0.7875],
        [0.1069, 0.5516, 0.9997, 0.7162],
        [0.3950, 0.6635, 0.8534, 0.1534]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
